#!/bin/bash
clear
###VARIAVEISDECOR###
pret="\033[1;30m"
verm="\033[1;31m"
verd="\033[1;32m"
ama="\033[1;33m"
azul="\033[1;34m"
purp="\033[1;35m"
cyan="\033[1;36m"
bran="\033[1;37m"
fi="\033[0m"
###FIMDASVARIAVEISDECOR###

#-------------------------------------------------------------------------#

varrriavel () {
for number in `(cat /tmp/tst1 | awk '{print $5}' |awk -F "[" '{print $2}' | awk -F "]" '{print $1}' | awk -F ":" '{print $1}')`
do
awkg=$(ps ax |grep dropbear |grep -o "$number")
if [ "$awkg" = "" ]; then
echo "" > /tmp/tmp
rm -rf /tmp/tmp
else
echo "$awkg" >> /tmp/$1
fi
done
}

#-------------------------------------------------------------------------#

lml () {
for limite in `(head -n $1 /tmp/$2)`
do
kill $limite
done
}

#-------------------------------------------------------------------------#

verify () {
#SCRIPT.SH USUARIO LIMITE                           
user="$1"
limit="$2"
cat /var/log/auth.log |grep "$user" > /tmp/tst1 
sleep 0.1s
perl -pi -e 's/Password auth succeeded for//g' /tmp/tst1
sleep 0.1s
perl -pi -e 's/dropbear//g' /tmp/tst1
sleep 0.1s
touch /tmp/$user
varrriavel $user
sleep 0.1s
num=$(cat /tmp/$user | wc -l)
killer=$(($num - $limit))
lml $killer $user
echo -e "\033[1;31mDesconectado $killer Usuário/s"
echo -e "\033[0m"
rm -rf /tmp/tst1
rm -rf /tmp/$user
}

#-------------------------------------------------------------------------#
varrr () {
for number in `(cat /tmp/tst1 | awk '{print $5}' |awk -F "[" '{print $2}' | awk -F "]" '{print $1}' | awk -F ":" '{print $1}')`
do
awkg=$(ps ax |grep dropbear |grep -c "$number")
if [ "$awkg" = "1" ]; then
echo "$awkg" >> /tmp/$1
fi
done
}

#-------------------------------------------------------------------------#

touch /tmp/ussh
cat /etc/passwd |grep -v ovpn > /tmp/ussh
touch /tmp/$1
touch /tmp/tst1
inte=$(cat /var/log/auth.log |grep "$1")
if [ "$inte" = "" ]; then
rm -rf /tmp/tst1
rm -rf /tmp/$1
kill $1
userdel --force $1
rm -rf /tmp/ussh
echo -e "Não esta online, Foi Apagado!"
exit
else
echo "$inte" > /tmp/tst1
fi
sleep 0.1s
perl -pi -e 's/Password auth succeeded for//g' /tmp/tst1
sleep 0.1s
perl -pi -e 's/dropbear//g' /tmp/tst1
sleep 0.1s
varrr $1
sleep 0.1s
num=$(cat /tmp/$1 | wc -l)
if [[ -e /etc/VpsPackdir/limite/$1 ]]; then
usrlimit="0"
else
usrlimit="0"
fi
rm -rf /tmp/tst1
rm -rf /tmp/$1
verify $1 $usrlimit
userdel --force $1
rm -rf /tmp/ussh
exit

